-- Apply this script only when BM_QUERY_COMPARISON already exists.

ALTER TABLE BM_QUERY_COMPARISON ADD (
    SCHEDULE_ENABLED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CRON_EXPRESSION VARCHAR2(100)
);

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_SCHEDULE_YN
    CHECK (SCHEDULE_ENABLED_YN IN ('Y', 'N'));

CREATE INDEX IX_BM_QC_SCHEDULE
    ON BM_QUERY_COMPARISON (SCHEDULE_ENABLED_YN, ENABLED_YN);

ALTER TABLE BM_QUERY_COMPARISON ADD (
    NOTIFY_ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    NOTIFY_ON_SUCCESS_YN CHAR(1) DEFAULT 'N' NOT NULL,
    NOTIFY_RECIPIENTS VARCHAR2(1000)
);

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_NOTIFY_YN
    CHECK (NOTIFY_ENABLED_YN IN ('Y', 'N'));

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_NOTIFY_SUCCESS_YN
    CHECK (NOTIFY_ON_SUCCESS_YN IN ('Y', 'N'));
