-- Adds OpenAI-backed SQL review and mismatch analysis fields.

ALTER TABLE BM_QUERY_COMPARISON ADD (
    AI_SQL_REVIEW_YN        CHAR(1) DEFAULT 'N' NOT NULL,
    AI_ANALYSIS_ENABLED_YN  CHAR(1) DEFAULT 'Y' NOT NULL,
    AI_SQL_REVIEW_STATUS    VARCHAR2(20),
    AI_SQL_REVIEW_SUMMARY   CLOB
);

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_AI_REVIEW_YN
    CHECK (AI_SQL_REVIEW_YN IN ('Y', 'N'));

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_AI_ANALYSIS_YN
    CHECK (AI_ANALYSIS_ENABLED_YN IN ('Y', 'N'));

ALTER TABLE BM_QUERY_COMPARISON_RESULT ADD (
    ORACLE_BATCH_CONTEXT CLOB,
    AI_ANALYSIS_STATUS   VARCHAR2(20),
    AI_ANALYSIS          CLOB,
    AI_ACTION_GUIDE      CLOB
);

ALTER TABLE BM_QUERY_EXPECTATION ADD (
    AI_SQL_REVIEW_YN      CHAR(1) DEFAULT 'N' NOT NULL,
    AI_SQL_REVIEW_STATUS  VARCHAR2(20),
    AI_SQL_REVIEW_SUMMARY CLOB
);

ALTER TABLE BM_QUERY_EXPECTATION ADD CONSTRAINT CK_BM_QE_AI_REVIEW_YN
    CHECK (AI_SQL_REVIEW_YN IN ('Y', 'N'));
