-- Apply this script when BM_QUERY_COMPARISON already exists and the
-- single-query validation/notification feature needs to be added.

ALTER TABLE BM_QUERY_COMPARISON ADD (
    NOTIFY_ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    NOTIFY_ON_SUCCESS_YN CHAR(1) DEFAULT 'N' NOT NULL,
    NOTIFY_RECIPIENTS VARCHAR2(1000)
);

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_NOTIFY_YN
    CHECK (NOTIFY_ENABLED_YN IN ('Y', 'N'));

ALTER TABLE BM_QUERY_COMPARISON ADD CONSTRAINT CK_BM_QC_NOTIFY_SUCCESS_YN
    CHECK (NOTIFY_ON_SUCCESS_YN IN ('Y', 'N'));

CREATE SEQUENCE BM_QUERY_EXPECTATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE BM_QUERY_EXPECT_RESULT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE BM_VALIDATION_NOTIFICATION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE BM_QUERY_EXPECTATION (
    EXPECTATION_ID          NUMBER(19)      NOT NULL,
    EXPECTATION_NAME        VARCHAR2(200)   NOT NULL,
    DESCRIPTION             VARCHAR2(1000),
    TARGET_DB_TYPE          VARCHAR2(20)    NOT NULL,
    QUERY_TEXT              CLOB            NOT NULL,
    EXPECTED_VALUE_TYPE     VARCHAR2(20)    NOT NULL,
    EXPECTED_OPERATOR       VARCHAR2(20)    NOT NULL,
    EXPECTED_VALUE          CLOB            NOT NULL,
    ENABLED_YN              CHAR(1)         DEFAULT 'Y' NOT NULL,
    SCHEDULE_ENABLED_YN     CHAR(1)         DEFAULT 'N' NOT NULL,
    CRON_EXPRESSION         VARCHAR2(100),
    NOTIFY_ENABLED_YN       CHAR(1)         DEFAULT 'Y' NOT NULL,
    NOTIFY_ON_SUCCESS_YN    CHAR(1)         DEFAULT 'N' NOT NULL,
    NOTIFY_RECIPIENTS       VARCHAR2(1000),
    AI_SQL_REVIEW_YN        CHAR(1)         DEFAULT 'N' NOT NULL,
    AI_SQL_REVIEW_STATUS    VARCHAR2(20),
    AI_SQL_REVIEW_SUMMARY   CLOB,
    CREATED_BY              VARCHAR2(100),
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY              VARCHAR2(100),
    UPDATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BM_QUERY_EXPECTATION PRIMARY KEY (EXPECTATION_ID),
    CONSTRAINT CK_BM_QE_DB_TYPE CHECK (TARGET_DB_TYPE IN ('SYBASE', 'ORACLE')),
    CONSTRAINT CK_BM_QE_VALUE_TYPE CHECK (EXPECTED_VALUE_TYPE IN ('SCALAR', 'ROW_COUNT', 'JSON', 'HASH')),
    CONSTRAINT CK_BM_QE_OPERATOR CHECK (EXPECTED_OPERATOR IN ('EQ', 'NE', 'GT', 'GTE', 'LT', 'LTE', 'CONTAINS')),
    CONSTRAINT CK_BM_QE_ENABLED_YN CHECK (ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_BM_QE_SCHEDULE_YN CHECK (SCHEDULE_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_BM_QE_NOTIFY_YN CHECK (NOTIFY_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_BM_QE_NOTIFY_SUCCESS_YN CHECK (NOTIFY_ON_SUCCESS_YN IN ('Y', 'N')),
    CONSTRAINT CK_BM_QE_AI_REVIEW_YN CHECK (AI_SQL_REVIEW_YN IN ('Y', 'N'))
);

CREATE TABLE BM_QUERY_EXPECTATION_RESULT (
    RESULT_ID               NUMBER(19)      NOT NULL,
    EXPECTATION_ID          NUMBER(19)      NOT NULL,
    REQUESTED_BY            VARCHAR2(100),
    REQUESTED_AT            TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT              TIMESTAMP,
    FINISHED_AT             TIMESTAMP,
    RESULT_STATUS           VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
    ACTUAL_ROW_COUNT        NUMBER(19),
    ACTUAL_VALUE            CLOB,
    ACTUAL_RESULT_HASH      VARCHAR2(128),
    EXPECTED_VALUE          CLOB,
    MISMATCH_SUMMARY        VARCHAR2(4000),
    ERROR_MESSAGE           CLOB,
    CONSTRAINT PK_BM_QUERY_EXPECTATION_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_BM_QER_EXPECTATION FOREIGN KEY (EXPECTATION_ID)
        REFERENCES BM_QUERY_EXPECTATION (EXPECTATION_ID),
    CONSTRAINT CK_BM_QER_STATUS CHECK (RESULT_STATUS IN ('REQUESTED', 'RUNNING', 'SUCCESS', 'FAIL', 'ERROR'))
);

CREATE TABLE BM_VALIDATION_NOTIFICATION (
    NOTIFICATION_ID         NUMBER(19)      NOT NULL,
    VALIDATION_TYPE         VARCHAR2(20)    NOT NULL,
    RULE_ID                 NUMBER(19)      NOT NULL,
    RESULT_ID               NUMBER(19)      NOT NULL,
    RESULT_STATUS           VARCHAR2(20)    NOT NULL,
    TITLE                   VARCHAR2(300)   NOT NULL,
    MESSAGE                 CLOB,
    RECIPIENTS              VARCHAR2(1000),
    READ_YN                 CHAR(1)         DEFAULT 'N' NOT NULL,
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BM_VALIDATION_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT CK_BM_VN_TYPE CHECK (VALIDATION_TYPE IN ('PAIR', 'SINGLE')),
    CONSTRAINT CK_BM_VN_READ_YN CHECK (READ_YN IN ('Y', 'N'))
);

CREATE INDEX IX_BM_QE_NAME ON BM_QUERY_EXPECTATION (EXPECTATION_NAME);
CREATE INDEX IX_BM_QE_ENABLED ON BM_QUERY_EXPECTATION (ENABLED_YN);
CREATE INDEX IX_BM_QE_SCHEDULE ON BM_QUERY_EXPECTATION (SCHEDULE_ENABLED_YN, ENABLED_YN);
CREATE INDEX IX_BM_QER_EXPECTATION ON BM_QUERY_EXPECTATION_RESULT (EXPECTATION_ID);
CREATE INDEX IX_BM_QER_STATUS_TIME ON BM_QUERY_EXPECTATION_RESULT (RESULT_STATUS, REQUESTED_AT DESC);
CREATE INDEX IX_BM_VN_CREATED ON BM_VALIDATION_NOTIFICATION (CREATED_AT DESC);
