CREATE SEQUENCE BM_QUERY_COMPARISON_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE BM_QUERY_COMPARE_RESULT_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE BM_QUERY_EXPECTATION_SEQ START WITH 200 INCREMENT BY 1;
CREATE SEQUENCE BM_QUERY_EXPECT_RESULT_SEQ START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE BM_VALIDATION_NOTIFICATION_SEQ START WITH 3000 INCREMENT BY 1;

CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_NAME VARCHAR2(100) NOT NULL,
    JOB_KEY VARCHAR2(2500)
);

CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT,
    JOB_INSTANCE_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR2(10),
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE CLOB,
    LAST_UPDATED TIMESTAMP,
    JOB_CONFIGURATION_LOCATION VARCHAR2(2500),
    CONSTRAINT FK_TEST_JOB_EXEC_INSTANCE FOREIGN KEY (JOB_INSTANCE_ID)
        REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
);

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID BIGINT NOT NULL,
    TYPE_CD VARCHAR2(6) NOT NULL,
    KEY_NAME VARCHAR2(100) NOT NULL,
    STRING_VAL VARCHAR2(250),
    DATE_VAL TIMESTAMP,
    LONG_VAL BIGINT,
    DOUBLE_VAL DOUBLE,
    IDENTIFYING CHAR(1) NOT NULL,
    CONSTRAINT FK_TEST_JOB_EXEC_PARAMS FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STEP_NAME VARCHAR2(100) NOT NULL,
    JOB_EXECUTION_ID BIGINT NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    STATUS VARCHAR2(10),
    COMMIT_COUNT BIGINT,
    READ_COUNT BIGINT,
    FILTER_COUNT BIGINT,
    WRITE_COUNT BIGINT,
    EXIT_CODE VARCHAR2(2500),
    EXIT_MESSAGE CLOB,
    READ_SKIP_COUNT BIGINT,
    WRITE_SKIP_COUNT BIGINT,
    PROCESS_SKIP_COUNT BIGINT,
    ROLLBACK_COUNT BIGINT,
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT FK_TEST_STEP_JOB_EXEC FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
);

CREATE TABLE BM_QUERY_COMPARISON (
    COMPARISON_ID NUMBER(19) NOT NULL,
    COMPARISON_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    SYBASE_QUERY CLOB NOT NULL,
    ORACLE_QUERY CLOB NOT NULL,
    COMPARE_MODE VARCHAR2(20) DEFAULT 'EXACT' NOT NULL,
    ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    SCHEDULE_ENABLED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CRON_EXPRESSION VARCHAR2(100),
    NOTIFY_ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    NOTIFY_ON_SUCCESS_YN CHAR(1) DEFAULT 'N' NOT NULL,
    NOTIFY_RECIPIENTS VARCHAR2(1000),
    AI_SQL_REVIEW_YN CHAR(1) DEFAULT 'N' NOT NULL,
    AI_ANALYSIS_ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    AI_SQL_REVIEW_STATUS VARCHAR2(20),
    AI_SQL_REVIEW_SUMMARY CLOB,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TEST_QUERY_COMPARISON PRIMARY KEY (COMPARISON_ID),
    CONSTRAINT CK_TEST_QC_COMPARE_MODE CHECK (COMPARE_MODE IN ('EXACT', 'HASH')),
    CONSTRAINT CK_TEST_QC_ENABLED_YN CHECK (ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QC_SCHEDULE_YN CHECK (SCHEDULE_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QC_NOTIFY_YN CHECK (NOTIFY_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QC_NOTIFY_SUCCESS_YN CHECK (NOTIFY_ON_SUCCESS_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QC_AI_REVIEW_YN CHECK (AI_SQL_REVIEW_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QC_AI_ANALYSIS_YN CHECK (AI_ANALYSIS_ENABLED_YN IN ('Y', 'N'))
);

CREATE TABLE BM_QUERY_COMPARISON_RESULT (
    RESULT_ID NUMBER(19) NOT NULL,
    COMPARISON_ID NUMBER(19) NOT NULL,
    REQUESTED_BY VARCHAR2(100),
    REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP,
    FINISHED_AT TIMESTAMP,
    RESULT_STATUS VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
    SYBASE_ROW_COUNT NUMBER(19),
    ORACLE_ROW_COUNT NUMBER(19),
    SYBASE_RESULT_HASH VARCHAR2(128),
    ORACLE_RESULT_HASH VARCHAR2(128),
    MISMATCH_SUMMARY VARCHAR2(4000),
    ERROR_MESSAGE CLOB,
    ORACLE_BATCH_CONTEXT CLOB,
    AI_ANALYSIS_STATUS VARCHAR2(20),
    AI_ANALYSIS CLOB,
    AI_ACTION_GUIDE CLOB,
    CONSTRAINT PK_TEST_QUERY_COMPARE_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_TEST_QCR_COMPARISON FOREIGN KEY (COMPARISON_ID)
        REFERENCES BM_QUERY_COMPARISON (COMPARISON_ID),
    CONSTRAINT CK_TEST_QCR_STATUS CHECK (RESULT_STATUS IN ('REQUESTED', 'RUNNING', 'SUCCESS', 'FAIL', 'ERROR'))
);

CREATE INDEX IX_TEST_QC_NAME ON BM_QUERY_COMPARISON (COMPARISON_NAME);
CREATE INDEX IX_TEST_QC_ENABLED ON BM_QUERY_COMPARISON (ENABLED_YN);
CREATE INDEX IX_TEST_QC_SCHEDULE ON BM_QUERY_COMPARISON (SCHEDULE_ENABLED_YN, ENABLED_YN);
CREATE INDEX IX_TEST_QCR_COMPARISON ON BM_QUERY_COMPARISON_RESULT (COMPARISON_ID);
CREATE INDEX IX_TEST_QCR_STATUS_TIME ON BM_QUERY_COMPARISON_RESULT (RESULT_STATUS, REQUESTED_AT DESC);

CREATE TABLE BM_QUERY_EXPECTATION (
    EXPECTATION_ID NUMBER(19) NOT NULL,
    EXPECTATION_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    TARGET_DB_TYPE VARCHAR2(20) NOT NULL,
    QUERY_TEXT CLOB NOT NULL,
    EXPECTED_VALUE_TYPE VARCHAR2(20) NOT NULL,
    EXPECTED_OPERATOR VARCHAR2(20) NOT NULL,
    EXPECTED_VALUE CLOB NOT NULL,
    ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    SCHEDULE_ENABLED_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CRON_EXPRESSION VARCHAR2(100),
    NOTIFY_ENABLED_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    NOTIFY_ON_SUCCESS_YN CHAR(1) DEFAULT 'N' NOT NULL,
    NOTIFY_RECIPIENTS VARCHAR2(1000),
    AI_SQL_REVIEW_YN CHAR(1) DEFAULT 'N' NOT NULL,
    AI_SQL_REVIEW_STATUS VARCHAR2(20),
    AI_SQL_REVIEW_SUMMARY CLOB,
    CREATED_BY VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TEST_QUERY_EXPECTATION PRIMARY KEY (EXPECTATION_ID),
    CONSTRAINT CK_TEST_QE_DB_TYPE CHECK (TARGET_DB_TYPE IN ('SYBASE', 'ORACLE')),
    CONSTRAINT CK_TEST_QE_VALUE_TYPE CHECK (EXPECTED_VALUE_TYPE IN ('SCALAR', 'ROW_COUNT', 'JSON', 'HASH')),
    CONSTRAINT CK_TEST_QE_OPERATOR CHECK (EXPECTED_OPERATOR IN ('EQ', 'NE', 'GT', 'GTE', 'LT', 'LTE', 'CONTAINS')),
    CONSTRAINT CK_TEST_QE_ENABLED_YN CHECK (ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QE_SCHEDULE_YN CHECK (SCHEDULE_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QE_NOTIFY_YN CHECK (NOTIFY_ENABLED_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QE_NOTIFY_SUCCESS_YN CHECK (NOTIFY_ON_SUCCESS_YN IN ('Y', 'N')),
    CONSTRAINT CK_TEST_QE_AI_REVIEW_YN CHECK (AI_SQL_REVIEW_YN IN ('Y', 'N'))
);

CREATE TABLE BM_QUERY_EXPECTATION_RESULT (
    RESULT_ID NUMBER(19) NOT NULL,
    EXPECTATION_ID NUMBER(19) NOT NULL,
    REQUESTED_BY VARCHAR2(100),
    REQUESTED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    STARTED_AT TIMESTAMP,
    FINISHED_AT TIMESTAMP,
    RESULT_STATUS VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
    ACTUAL_ROW_COUNT NUMBER(19),
    ACTUAL_VALUE CLOB,
    ACTUAL_RESULT_HASH VARCHAR2(128),
    EXPECTED_VALUE CLOB,
    MISMATCH_SUMMARY VARCHAR2(4000),
    ERROR_MESSAGE CLOB,
    CONSTRAINT PK_TEST_QUERY_EXPECTATION_RESULT PRIMARY KEY (RESULT_ID),
    CONSTRAINT FK_TEST_QER_EXPECTATION FOREIGN KEY (EXPECTATION_ID)
        REFERENCES BM_QUERY_EXPECTATION (EXPECTATION_ID),
    CONSTRAINT CK_TEST_QER_STATUS CHECK (RESULT_STATUS IN ('REQUESTED', 'RUNNING', 'SUCCESS', 'FAIL', 'ERROR'))
);

CREATE TABLE BM_VALIDATION_NOTIFICATION (
    NOTIFICATION_ID NUMBER(19) NOT NULL,
    VALIDATION_TYPE VARCHAR2(20) NOT NULL,
    RULE_ID NUMBER(19) NOT NULL,
    RESULT_ID NUMBER(19) NOT NULL,
    RESULT_STATUS VARCHAR2(20) NOT NULL,
    TITLE VARCHAR2(300) NOT NULL,
    MESSAGE CLOB,
    RECIPIENTS VARCHAR2(1000),
    READ_YN CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TEST_VALIDATION_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
    CONSTRAINT CK_TEST_VN_TYPE CHECK (VALIDATION_TYPE IN ('PAIR', 'SINGLE')),
    CONSTRAINT CK_TEST_VN_READ_YN CHECK (READ_YN IN ('Y', 'N'))
);

CREATE INDEX IX_TEST_QE_NAME ON BM_QUERY_EXPECTATION (EXPECTATION_NAME);
CREATE INDEX IX_TEST_QE_ENABLED ON BM_QUERY_EXPECTATION (ENABLED_YN);
CREATE INDEX IX_TEST_QE_SCHEDULE ON BM_QUERY_EXPECTATION (SCHEDULE_ENABLED_YN, ENABLED_YN);
CREATE INDEX IX_TEST_QER_EXPECTATION ON BM_QUERY_EXPECTATION_RESULT (EXPECTATION_ID);
CREATE INDEX IX_TEST_QER_STATUS_TIME ON BM_QUERY_EXPECTATION_RESULT (RESULT_STATUS, REQUESTED_AT DESC);
CREATE INDEX IX_TEST_VN_CREATED ON BM_VALIDATION_NOTIFICATION (CREATED_AT DESC);

CREATE TABLE SETTLEMENT (
    BUSINESS_DATE VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER(19, 2) NOT NULL
);

CREATE TABLE CUSTOMER_MASTER (
    CUSTOMER_ID BIGINT NOT NULL PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    USE_YN CHAR(1) NOT NULL
);
